---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12
  data_bags_path: data_bags
  client_rb:
    environment: vagrant

platforms:
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04
  - name: ubuntu-12.04
    driver:
      box: express42/ubuntu12.04-chef11

suites:
  - name: base
    run_list:
      - role[base]
  - name: chef-server
    run_list:
      - role[base]
      - role[chef-server]
  - name: graylog-server
    run_list:
      - role[base]
      - role[graylog-server]
  - name: zabbix-server
    run_list:
      - role[base]
      - role[zabbix-server]
