language: ruby
rvm:
- 2.1.5
bundler_args: "--without kitchen_vagrant"
before_install:
- openssl aes-256-cbc -K $encrypted_19d896899cd0_key -iv $encrypted_19d896899cd0_iv
  -in .travis/secret_keys.tar.enc -out .travis/secret_keys.tar -d
- tar xf .travis/secret_keys.tar -C .travis
- mv .travis/travis_rsa ~/.ssh/id_rsa
script:
- bundle exec rubocop
- bundle exec kitchen test -d always
notifications:
  slack:
    secure: 2gogsRTMlBlwV4J7OLQYTPQAlVgd3tsFwwMNk1Xco3acAcqa2SjjLMbZRGc/rfjqU7+c32QDsGSwGEmGzX94svaE592ZGr8SK4YiXlDEQbs3JkSxJ1SutNzwZx9ZJFfSokSCYe3BWMg6983kK5bNZ6U525pBnZSURHG+U0KLftg=
env:
  global:
  - secure: JbFfHuaVanHRBQ6sZXPD5IfA6+hOM5JzhiHlXHrD20onqApbIobT6qmKz0pGb/XGoO4MPpJDd+4jdAB6RZuHzoLsbfUOog8jKkf8yuEZy3BEsq2sQGH3ShfwY5AazSLxDn9L1FphG4/vsIxjyoKQmN6+9CZtokRagHUS8tGxIE0=
  - secure: udWXbgonf5gw1i0Hgs2Gf9E+po7foBLlZBkwYMC7VuBgjF0NqRu7LLOlz+I5GSmSfPe/P2fpkFrq0uiMtJpECKqpMsvPiPx1lYphDWe5Ev2luGSwNycCpJV5tB/AqDSicCnT/3wrl4VCLSw6xeOkxsA6AYE0b4eMrHQfg3slxrc=
